<!-- This file was generated by npm create vue -->
<template>
  <Navbar />
  <div class="main-content">
    <RouterView />
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Navbar from './components/Navbar.vue';
</script>

<style>
/* Adjust padding to match your navbar height */
.main-content {
  padding-top: 60px; /* Adjust if needed */
}
</style>