services:
  discogs_db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_discogs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./test/init_discogs.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  forum_db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./test/init_users.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

