name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test_discogs_db:
        image: postgres:13
        env:
          POSTGRES_DB: test_discogs_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      test_users_db:
        image: postgres:13
        env:
          POSTGRES_DB: test_users_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5433; do sleep 1; done
          until pg_isready -h localhost -p 5434; do sleep 1; done
      - name: Run tests
        run: |
          cd server
          python3 -m unittest discover test -b
